---
title: "Untitled"
output: html_document
---


```{r pressure, echo=FALSE}
# library(fs)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


```{r}
old_hms_dir = system.file(package = 'hms')
my_temp = tempdir()
list.files(my_temp)
file.copy(old_hms_dir, my_temp, recursive = TRUE) 
list.files(my_temp)
new_hms = file.path(my_temp, "hms")
library(hms, lib.loc = my_temp)
system.file(package = 'hms')
# sessionInfo()
```
```{r}
# library(dplyr)
# library(fs)
# library(tibble)
# system.file(package = 'fs')

```


```{r}
.libPaths(my_temp)
system.file(package = 'hms')
```
```{r}
.libPaths() 
```
```{r}
.Library.site
```

```{r}
.Library
```
```{r}
# Sys.getenv("R_LIBS")
Sys.getenv("R_LIBS_USER")
# Sys.getenv("R_LIBS_SITE")
Sys.setenv(TMP_R_LIB=my_temp)
```
```{bash}
Rscript -e "print ('help')"
Rscript -e "system.file(package = 'hms')"
export R_LIBS_USER=$TMP_R_LIB
Rscript -e "system.file(package = 'hms')"
Rscript -e "library('hms')"

```



```{r}
system.file(package = 'rlang')
```

