BootStrap: shub
From: granek/singularity-rstudio-tidyverse:3.5.2

%labels
    Maintainer Josh Granek
    Image_Version 0002

##------------------------------------------------------------
## Build example:
## sudo singularity build mar1_rstudio_v0002.simg Singularity.mar1
## sudo singularity build ~/container_images/mar1_rstudio_v0002.simg Singularity.mar1

##
## Run example:
## singularity run canu_rstudio.simg ls
## singularity run --app rstudio canu_rstudio.simg
##------------------------------------------------------------

%runscript
  exec "${@}"

%apprun rstudio
  exec rserver "${@}"

%environment
  export PATH=/usr/lib/rstudio-server/bin:${PATH}
  export CONDA_DIR=/opt/conda
  export PATH=$PATH:$CONDA_DIR/bin
  export SHELL=/bin/bash
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8

%post
  # Install extra stuff
  apt-get update
  apt-get install -y --no-install-recommends \
    curl \
    wget \
    bzip2 \
    parallel \
    bwa \
    samtools \
    ncbi-blast+ \
    mafft \
    git \
    ssh \
    emacs \
    less \
    make \
    libxml2-dev \
    libgsl0-dev \
    libglu1-mesa \
    libmariadb-client-lgpl-dev \
    seqtk \
    rna-star \
    htop
   apt-get clean
   rm -rf /var/lib/apt/lists/*

#--------------------------------------------------------------------------------
Rscript -e "install.packages(pkgs = c('argparse','R.utils','fs','here'), \
    repos='https://cran.revolutionanalytics.com/', \
    dependencies=TRUE, \
    clean = TRUE)"

Rscript -e "if (!requireNamespace('BiocManager')){install.packages('BiocManager')}; \
    BiocManager::install(); \
    BiocManager::install(c('ggbio','GenomicRanges','rtracklayer', 'DESeq2'))"

##------------------------------------------------------------
CONDA_DIR=/opt/conda
cd /tmp && \
    mkdir -p $CONDA_DIR && \
    wget --quiet https://repo.continuum.io/miniconda/Miniconda3-4.4.10-Linux-x86_64.sh && \
    echo "bec6203dbb2f53011e974e9bf4d46e93 Miniconda3-4.4.10-Linux-x86_64.sh" | md5sum -c - && \
    /bin/bash Miniconda3-4.4.10-Linux-x86_64.sh -f -b -p $CONDA_DIR && \
    rm Miniconda3-4.4.10-Linux-x86_64.sh && \
    $CONDA_DIR/bin/conda clean -tipsy

$CONDA_DIR/bin/conda install -c bioconda biopython gatk sra-tools samtools bwakit bwa bcftools ea-utils && \
    $CONDA_DIR/bin/conda clean -tipsy

$CONDA_DIR/bin/conda install -c bioconda mosdepth && \
    $CONDA_DIR/bin/conda clean -tipsy

#--------------------------------------------------------------------------------
pip install DukeDSClient
#--------------------------------------------------------------------------------

mkdir -p /data
mkdir -p /workspace

# Helpful:
#------------------
# https://gitlab.oit.duke.edu/mccahill/jupyter-HTS-2017/blob/master/Dockerfile
# https://github.com/nickjer/singularity-r/blob/master/Singularity.3.4.3
# https://github.com/nickjer/singularity-rstudio/blob/master/Singularity
# https://www.singularity-hub.org/collections/174
# https://www.singularity-hub.org/collections/463

# sudo singularity build canu_rstudio.simg singularity_canu_rstudio

