BootStrap: library
From: granek/duke-chsi-informatics/singularity-rnaseq:0005

%labels
    Maintainer Josh Granek
    Image_Name rna_enrichment
    Image_Version rna_enrichment_0005

%post
  Rscript -e "install.packages(pkgs = c('rstatix','ggpubr','rentrez'), repos='https://mirror.las.iastate.edu/CRAN/', dependencies=TRUE, clean = TRUE)"
  pip3 install --no-cache-dir \
    RSeQC

  #------------------
  # Install Bioconductor Packages
  #------------------
  Rscript -e "if (!requireNamespace('BiocManager')){install.packages('BiocManager')}; BiocManager::install(); BiocManager::install(c('GEOquery','CoverageView','bamsignals'))"

  mkdir -p /space
