---
title: "Enrichment Correlation"
output: html_document
---

```{r}
source("run_config.R")
library(foreach)
library(tidyverse)
library(magrittr)
```





```{r}
count_suffix = "_ReadsPerGene.out.tab"
countfiles = list.files(starout.dir, pattern = paste0(count_suffix,"$"), full.names = TRUE)
countfiles
```

```{r}
countfiles %>%
  path_file %>%
  str_replace(count_suffix,"")

```

## Load STAR Count Data
### Load STAR Count tables into a single dataframe

Loading code borrowed from https://gitlab.oit.duke.edu/HTS2018/HTS2018-notebooks/blob/master/pilot/01_Read_Counts.ipynb


```{r}
mycombine <- function(df1, df2) {
    # Combine two data frames by gene names
    #
    # Args:
    #   df1 (Dataframe): the first count data
    #   df2 (Dataframe): the second count data
    #
    # Returns:
    #   (Dataframe) The combined data frame of df1 and df2
    full_join(df1, df2, by = "gene")
}

# Data type for each column
coltypes <- list(col_character(), col_integer(), col_integer(), col_integer())

out <- foreach(count_path = countfiles, .combine = mycombine) %do% {
  # generate rowname (extracted from count file name)
  count_path %>%
    path_file %>%
    str_replace(count_suffix,"") ->
    readset_label 

    # read in the count file
    readr::read_tsv(count_path, col_names = FALSE, col_types = coltypes) %>%
        dplyr::select(X1, X4) %>% # get the 1st and 4th columns (gene ids and second strand read counts)
            dplyr::rename_(.dots=setNames(names(.), c("gene",readset_label)))
}

out[1:6,1:6]


out %>%
    dplyr::slice(-(1:4)) %>%
    gather(expid, value, -gene) %>% 
    spread(gene, value) -> genecounts

genecounts[1:6,1:6]

```

### Add metadata to STAR count dataframe
```{r}
genecounts %>%
  mutate(Label=str_extract(expid, "^\\d+_[A-Z]+_[A-Z]")) %>%
  select(Label, everything()) %>%
  select(-expid) ->
  genecounts_with_label
genecounts_with_label[1:4,1:6]

```

```{r}
79+79+81+61
30+35+36+36
38+32+37+50
```
```{r}
genecounts_with_label[5:8,1:6]

```
```{r}
43+39+47+39
```

### Combine per library counts across lanes

```{r}
genecounts_with_label %>%
  group_by(Label) %>%
  summarise_all(funs(sum)) ->
  genecounts_lanes_combined

# Add metadata 
read_tsv(metadata.file) %>%
  select(Label, enrichment_method, RNA_sample_num) ->
  metadata.df

genecounts_lanes_combined %<>%
  left_join(metadata.df, by="Label") %>%
  select(Label, enrichment_method, RNA_sample_num, everything())
genecounts_lanes_combined[,1:6]
```

```{r}


genecounts_lanes_combined[,1:6]
```

```{r}
read_tsv(metadata.file) %>%
  select(Label, enrichment_method, RNA_sample_num) ->
  metadata.df

genecounts_lanes_combined %<>%
  left_join(metadata.df, by="Label") %>%
  select(Label, enrichment_method, RNA_sample_num, everything())
#   genecounts_with_meta
# 
# genecounts %>%
#   mutate(Label=str_extract(expid, "^\\d+_[A-Z]+_[A-Z]"), 
#          lane=str_extract(expid, "L\\d{3}$")) %>%
#   left_join(metadata.df, by="Label") %>%
#   select(expid, Label, lane, everything()) ->
#   genecounts_with_meta
# 
# metadata.df
# genecounts_with_meta[1:6,1:6]
# ncol(metadata.df)
# ncol(genecounts)
# ncol(genecounts_with_meta)
# 
# ncol(genecounts_with_meta)
# 
genecounts_lanes_combined
```



```{r}
genecounts_with_label %>% 
genecounts %>%
  mutate(Label=str_extract(expid, "^\\d+_[A-Z]+_[A-Z]")) %>%
  select(Label, everything()) %>%
  select(-expid) ->
  genecounts_with_label
genecounts_with_label[1:6,1:6]
```

```{r}
genecounts %>%
  mutate(Label=str_extract(expid, "^\\d+_[A-Z]+_[A-Z]"), 
         lane=str_extract(expid, "L\\d{3}$")) %>%
  select(expid, Label, lane, everything()) ->
  genecounts_with_label
genecounts_with_label[1:6,1:6]
```

```{r}


metadata.df = read_tsv(metadata.file)

genecounts %>%
  mutate(Label=str_extract(expid, "^\\d+_[A-Z]+_[A-Z]"), 
         lane=str_extract(expid, "L\\d{3}$")) %>%
  left_join(metadata.df, by="Label") %>%
  select(expid, Label, lane, everything()) ->
  genecounts_with_meta

metadata.df
genecounts_with_meta[1:6,1:6]
ncol(metadata.df)
ncol(genecounts)
ncol(genecounts_with_meta)

ncol(genecounts_with_meta)

```
### Combine per library counts across lanes
```{r}
# genecounts_with_meta %>%
#   colnames %>%
#   str_detect(., "CNAG", negate = FALSE))

genecounts_with_meta %>%
  colnames %>%
  grep("CNAG|ENSRNA", ., value = TRUE, invert = TRUE)

# genecounts_with_meta %>%
#   group_by(Label) %>%
#   summarise_all(funs(sum)) ->
#   genecounts_with_meta_lanes_combined
# 
# genecounts_with_meta_lanes_combined[1:6,1:6]

starts_with()
```



