---
title: "Run rRNA Analysis"
output:
  html_document:
    toc: false
---


```{r load_libraries}
library(here)
library(dplyr)
library(fs)
library(rmarkdown)
library(magrittr)
library(utils)
```

```{r set_paths}
source("run_config.R")
```

```{r prepare_output_dir}
if (dir_exists(out.dir)) {dir_delete(out.dir)}

regression_output_dir = file.path(out.dir, "full_run_html")
dir.create(regression_output_dir, recursive = TRUE)
```

```{r find_rmds, eval=FALSE, include=TRUE}
list.files(pattern = ".Rmd") ->
  all_rmd_vector

ordered_rmds_to_run = c(
  "download_data.Rmd", 
  "run_star_on_total_samples.Rmd",
  "coverage_plot_play.Rmd", 
  "generate_rnaseh_oligos.Rmd",
  "check_rnaseh_oligos.Rmd",
  "tally_rrna_reads.Rmd",
  "run_star_on_enrich_compare_samples.Rmd",
  "enrichment_correlation.Rmd"
  )

cat(paste("Rmds not run by this meta script:", paste(setdiff(all_rmd_vector, ordered_rmds_to_run), collapse="\n"), sep="\n"))
```

```{r run_render}
#R -e "rmarkdown::render('run_full_lemur_data.Rmd',output_file='run_full_lemur_data.html')"

for (cur_rmd in ordered_rmds_to_run){
  print(cur_rmd)
  path_file(cur_rmd) %>%
    path_ext_set("html") %>%
    file.path(regression_output_dir, .) ->
    cur_out
  render(cur_rmd, output_file=cur_out, output_format="html_document")
}
```

```{r make_igv_package}
files_to_tar = c(gtf_with_mito_rrna.file, 
                 fa_for_mito_rrna.file,
                 rrna_oligos.file,
                 list.files(RRNA_OLIGO_STAROUT.dir, 
                            pattern = ".bam", 
                            full.names = TRUE)
                 )

tar(igv_tarball, 
    files=files_to_tar,
    compression="gzip", 
    tar = "/bin/tar")
print(igv_tarball)
```

# SessionInfo
```{r session_info}
sessionInfo()
```
