---
title: "Run rRNA Analysis"
output:
  html_document:
    toc: false
---

Rscript -e "rmarkdown::render('meta_run_rrna_analysis_2019.Rmd')"

```{r setup_metarun}
source("run_config_2019.R")

library(knitr)
library(rmarkdown)
library(callr)
# library(here)
# library(dplyr)
# library(fs)
# library(magrittr)
# library(utils)
```

```{r prepare_output_dir}

if (dir_exists(out.dir)) {dir_delete(out.dir)}
```

```{r find_rmds}
list.files(pattern = ".Rmd") ->
  all_rmd_vector

ordered_rmds_to_run = c(
  "run_star_on_enrich_samples.Rmd",
  "tally_rrna_reads_2019.Rmd",
  "enrichment_correlation_combined.Rmd")

cat(paste("Rmds not run by this meta script:", paste(setdiff(all_rmd_vector, ordered_rmds_to_run), collapse="\n"), sep="\n"), fill=TRUE)

warning("several Rmds in this directory are not being run!!!")
```

```{r}
for (cur_rmd in ordered_rmds_to_run) {
  print(cur_rmd)
  path_file(cur_rmd) %>%
    path_ext_set("html") %>%
    file.path(knit_output_dir, .) ->
    cur_out
  # Run render in callr::r to avoid library leakage between Rmds. This fixes a problem knitting enrichment_correlation.Rmd
  callr::r(
    function(input, output_file, output_format) {
      rmarkdown::render(input = input,
                        output_file = output_file,
                        output_format = output_format)
    },
    args = list(
      input = cur_rmd,
      output_file = cur_out,
      output_format = "html_document"
    )
  )
  cat("RENDERED:", cur_out, fill = TRUE)
}
```

# SessionInfo
```{r session_info}
sessionInfo()
```
