---
title: "plotting_bar_graphs"
output: html_document
---

```{r global_options, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo=FALSE, include=FALSE)
```

```{r}
# install.packages("rstatix")
# install.packages("ggpubr")
# install.packages("tibble")
```

```{r}
###2019 data
rrna_data_2019 <- read.csv(file.choose("rrna_depletion_calculation_2019.csv"))
levels(rrna_data_2019$Sample)
rrna_data_2019$Sample <- ordered(rrna_data_2019$Sample, levels = c("Total", "Poly(A)", "RNaseH"))
levels(rrna_data_2019$Sample)
 
library(rstatix)
stat.test_2019 <- aov(log_tranform_ratio ~ Sample, data = rrna_data_2019) %>%
  tukey_hsd()
stat.test_2019 

library("ggpubr")
ggbarplot(rrna_data_2019, x = "Sample", y = "percent_rrna", add = c("mean_se"),
          position = position_dodge(),
          color = "black", palette = c("#A7A8A8", "#BBEFFA", "#DFAEC3"),
          fill = "Sample",
          ylim = c(0, 100),
          order = c("Total", "Poly(A)", "RNaseH"),
          legend = "none",
          ylab = "rRNA reads (% total reads)", xlab = " ") +
  stat_pvalue_manual(
    stat.test_2019, label = "p.adj.signif", 
    tip.length = 0,
    size = 6,
    bracket.size = 0.75,
    y.position = c(95, 100, 8.5))
```

```{r}
###2018 data
rrna_data_2018 <- read.csv(file.choose("rrna_depletion_calculation_2018.csv"))
levels(rrna_data_2018$Sample)
rrna_data_2018$Sample <- ordered(rrna_data_2018$Sample, levels = c("Total", "Poly(A)", "RiboZero"))
levels(rrna_data_2018$Sample)

library(rstatix)
stat.test_2018 <- aov(log_tranform_ratio ~ Sample, data = rrna_data_2018) %>%
  tukey_hsd()
stat.test_2018 

library("ggpubr")
ggbarplot(rrna_data_2018, x = "Sample", y = "percent_rrna", add = c("mean_se"),
          position = position_dodge(),
          color = "black", palette = c("#A7A8A8", "#BBEFFA", "#C2F5D4"),
          fill = "Sample",
          ylim = c(0, 100),
          order = c("Total", "Poly(A)", "RiboZero"),
          legend = "none",
          ylab = "rRNA reads (% total reads)", xlab = " ") +
  stat_pvalue_manual(
    stat.test_2018, label = "p.adj.signif", 
    tip.length = 0,
    size = 6,
    bracket.size = 0.75,
    y.position = c(95, 100, 69))

```

```{r}
###bio replicate data
bio_rep_data <- read.csv(file.choose("biological_replicate_plot.csv"))
levels(bio_rep_data$Sample)

ggbarplot(bio_rep_data, x = "Sample", y = "Average_corr_coeff", add = c("mean_se"),
          position = position_dodge(),
          color = "black", fill = c("#bebebe"),
          ylim = c(0, 1),
          legend = "none",
          ylab = "Average Correlation Coefficient", xlab = " ")

```

```{r}
###protein coding data
protein_coding_data <- read.csv(file.choose("protein_coding_plot.csv"))
levels(protein_coding_data$Sample)
protein_coding_data$Sample <- ordered(protein_coding_data$Sample, levels = c("RNaseH", "Poly(A)"))
levels(protein_coding_data$Sample)

ggbarplot(protein_coding_data, x = "Sample", y = "Average_corr_coeff", add = c("mean_se"),
          position = position_dodge(),
          color = "black", palette = c("#00bfc4", "#f8766d"),
          fill = "Sample",
          ylim = c(0, 1),
          order = c("RNaseH", "Poly(A)"),
          legend = "none",
          ylab = "Average Correlation Coefficient", xlab = "")
```

```{r}
###ncRNA data
ncrna_data <- read.csv(file.choose("ncrna_plot.csv"))
levels(ncrna_data$Sample)
ncrna_data$Sample <- ordered(ncrna_data$Sample, levels = c("RNaseH", "Poly(A)"))
levels(ncrna_data$Sample)

ggbarplot(ncrna_data, x = "Sample", y = "Average_corr_coeff", add = c("mean_se"),
          position = position_dodge(),
          color = "black", palette = c("#00bfc4", "#f8766d"),
          fill = "Sample",
          ylim = c(0, 1),
          order = c("RNaseH", "Poly(A)"),
          legend = "none",
          ylab = "Average Correlation Coefficient", xlab = "")
```