---
title: "Tally rRNA Reads"
output: html_document
---

```{r global_options, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo=FALSE, include=FALSE)
```

```{r}
source("run_config_2019.R")

library(GenomicFeatures)
library(Rsamtools)
library(rtracklayer)
library(stringr)
library(tibble)
library(readr)
library(ggplot2)
library(magrittr)
library(rstatix)
library(ggpubr)
```

## Determine rRNA Counts
```{r}
countsFromBam <- function(bam_file, gene_granges) {
  countBam(bam_file,
           param=ScanBamParam(which=gene_granges)) ->
    count_tab

  count_tab %>%
    pull(records) %>%
    sum %>%
    return
}

summarizeStarCounts <- function(star_count_file) {
  read_tsv(star_count_file, 
         col_names = c("gene_id", "unstranded", "first_strand", "second_strand")) ->
    star_counts
  
  star_counts %>%
    summarise(total = sum(second_strand))%>%
    pull(total) ->
    total_reads
  
  ### 3. Calculate "strand mapped reads" as sum of "second_strand" column minus "unmapped" reads from that column
  
  star_counts %>%
    filter(gene_id != "N_unmapped") %>%
    summarise(total = sum(second_strand))%>%
    pull(total) ->
    mapped_reads
  
  # total_reads
  # mapped_reads
  return(c(total_reads=total_reads, mapped_reads=mapped_reads))
}

percentRRNA = function(gtf_path, star_out_dir, bam_subset_regex=".*"){
  import(gtf_path, format="gtf") %>%
    subset(gene_biotype=="rRNA") %>%
    subset(type=="exon") ->
    rrna_granges
  #-------------------------------------
  list.files(star_out_dir, pattern = paste0(bam_suffix,"$"), full.names = TRUE) %>%
    path_filter(regex=bam_subset_regex) ->
    bamfiles

  countfiles = bamfiles %>%
    str_replace(bam_suffix, count_suffix)
  #-------------------------------------
  # print(bamfiles)
  # print(countfiles)
  #-------------------------------------
  bam_counts = as.data.frame(sapply(bamfiles, countsFromBam, rrna_granges)) %>%
    rownames_to_column  %>%
    mutate(sample=path_file(rowname)) %>%
    mutate(sample=str_replace(sample, bam_suffix,"")) %>%
    dplyr::select(sample, rrna_reads=2 )

  
  star_counts = t(sapply(countfiles, summarizeStarCounts)) %>%
    as.data.frame %>%
    rownames_to_column %>%
    mutate(sample=path_file(rowname)) %>%
    mutate(sample=str_replace(sample, count_suffix,"")) %>%
    dplyr::select(sample, total_reads, mapped_reads)
  
  star_counts
  
  combined_counts = full_join(star_counts, bam_counts, by="sample") %>%
    mutate(percent_mapped = 100 * mapped_reads/total_reads,
           rrna_percent_total = 100 * rrna_reads/total_reads,
           rrna_percent_mapped = 100 * rrna_reads/mapped_reads)

  # return(list(bam_counts, star_counts))
  return(combined_counts)

# 1. Use RSamtools to count reads mapping to rRNA genes
# 2. Calculate "total_reads" as sum of "second_strand" column
# 3. Calculate "strand mapped reads" as sum of "second_strand" column minus "unmapped" reads from that column
# 4. calculate rRNA_reads/total_reads and rRNA_reads/mapped_reads for each of the 2018 Total libraries
}
```




```{r}
enrich_compare_counts = percentRRNA(gtf_with_mito_rrna.file, enrich_compare_starout.dir, bam_subset_regex="_2018_P_")
```

## Merge rRNA Counts with Metadata

```{r}
enrich_compare_counts[1:6,1:6]
```


```{r}
metadata.df = read_tsv(metadata.file)

enrich_compare_counts %>%
  mutate(Label=str_extract(sample, "^\\d+_\\d+_[A-Z]_[HMT]\\d"), 
         lane=str_extract(sample, "L\\d{3}$")) %>%
  left_join(metadata.df, by="Label") %>%
  mutate(sequencing_year="2019")->
  enrich_compare_counts_with_meta

kable(enrich_compare_counts_with_meta)
```

## rRNA Reads as a portion of Total Reads
```{r percent_rrna_plot}

enrich_compare_counts_with_meta %<>%
   mutate(enrichment_method = factor(enrichment_method, 
                                     levels = c("Total", "RNaseH", "mRNA")))

ggplot(data=enrich_compare_counts_with_meta, 
       aes(x=RNA_sample_num, y=rrna_percent_total, fill=lane)) +
  geom_bar(stat="identity", 
           position = position_dodge(preserve = "total"),
           color="black") +
  facet_grid(cols = vars(enrichment_method), scale="free_x") +
  scale_fill_brewer(guide=FALSE) +
  theme_bw() +
  labs(x = "Sample", y="% rRNA reads") +
  ylim(c(0,100)) ->
  percent_rrna.plot

percent_rrna.plot

```

### Prettier Figure for Publication
#### Summarize Across Lanes
```{r}
enrich_compare_counts_with_meta %>%
  mutate(enrichment_method=str_replace(enrichment_method,pattern="mRNA",replacement="Poly(A)"),
         enrichment_method=factor(enrichment_method, levels = c("Total", "Poly(A)", "RNaseH"))) %>%
  group_by(enrichment_method, RNA_sample_num, sample_year, genotype, condition) %>%
  summarise(
    total_reads=sum(total_reads),
    mapped_reads=sum(mapped_reads),
    rrna_reads=sum(rrna_reads)) %>%
  mutate(ratio_rrna=rrna_reads/total_reads,
         percent_rrna=ratio_rrna*100,
         log_tranform_ratio=log10(ratio_rrna)) ->
  rrna_data_2019
# rrna_data_2019
```

#### Make Pretty BarPlot
```{r}
# This chunk modified from plotting_bar_graphs.Rmd

stat.test_2019 <- aov(log_tranform_ratio ~ enrichment_method, data = rrna_data_2019) %>%
  tukey_hsd()
# stat.test_2019 

ggbarplot(rrna_data_2019, x = "enrichment_method", y = "percent_rrna", add = c("mean_se"),
          position = position_dodge(),
          color = "black", palette = c("#A7A8A8", "#BBEFFA", "#DFAEC3"),
          fill = "enrichment_method",
          ylim = c(0, 100),
          order = c("Total", "Poly(A)", "RNaseH"),
          legend = "none",
          ylab = "rRNA reads (% total reads)", xlab = " ") +
  stat_pvalue_manual(
    stat.test_2019, label = "p.adj.signif", 
    tip.length = 0,
    size = 6,
    bracket.size = 0.75,
    y.position = c(95, 100, 8.5))
```

## Mapped Reads as a portion of Total Reads
```{r}
ggplot(data=enrich_compare_counts_with_meta, 
       aes(x=RNA_sample_num, y=percent_mapped, fill=lane)) +
  geom_bar(stat="identity", 
           position = position_dodge(preserve = "total"),
           color="black") +
  facet_grid(cols = vars(enrichment_method), scale="free_x") +
  scale_fill_brewer(guide=FALSE) +
  theme_bw() +
  labs(x = "Sample", y="% Reads Mapped") +
  ylim(c(0,100))
```

# Include 2018 Data

```{r}
list.files(RZ_enrich_samples_starout.dir)
```


```{r}
full_data_counts_2018 = percentRRNA(gtf_with_mito_rrna.file, RZ_enrich_samples_starout.dir)
```

```{r include=TRUE}
metadata.df = read_tsv(metadata_2018.file)

enrichment_names <- c(
                    "MA" = "Poly(A)",
                    "RZ" = "RiboZero",
                    "TOT" = "Total")

full_data_counts_2018 %>%
  mutate(Label=str_extract(sample, "^\\d+_[A-Z]+_[A-Z]"), 
         lane=str_extract(sample, "L\\d{3}$")) %>%
  left_join(metadata.df, by="Label") %>%
  mutate(enrichment_method=str_replace_all(enrichment_method, enrichment_names),
         sequencing_year="2018") ->
  full_data_counts_2018_with_meta

# kable(full_data_counts_2018_with_meta)
full_data_counts_2018_with_meta
```

```{r include=TRUE}
ggplot(data=full_data_counts_2018_with_meta, 
       aes(x=RNA_sample_num, y=rrna_percent_total, fill=lane)) +
  geom_bar(stat="identity", 
           position = position_dodge(preserve = "total"),
           color="black") +
  facet_grid(cols = vars(enrichment_method), scale="free_x") +
  scale_fill_brewer(guide=FALSE) +
  theme_bw() +
  labs(x = "Sample", y="% rRNA reads") +
  ylim(c(0,100))
```

### Prettier Figure for Publication

#### Summarize Across Lanes

```{r}
full_data_counts_2018_with_meta %>%
  mutate(enrichment_method=factor(enrichment_method, levels = c("Total", "Poly(A)", "RiboZero"))) %>%
  group_by(enrichment_method, RNA_sample_num, Strain, Media) %>%
  summarise(
    total_reads=sum(total_reads),
    mapped_reads=sum(mapped_reads),
    rrna_reads=sum(rrna_reads)) %>%
  mutate(ratio_rrna=rrna_reads/total_reads,
         percent_rrna=ratio_rrna*100,
         log_tranform_ratio=log10(ratio_rrna)) ->
  rrna_data_2018

rrna_data_2018 %>%
  kable
```

#### Make Pretty BarPlot
```{r}
# This chunk modified from plotting_bar_graphs.Rmd
rrna_data_2018 %>%
  aov(log_tranform_ratio ~ enrichment_method, data = .) %>%
  tukey_hsd ->
  stat.test_2018

# stat.test_2018

rrna_data_2018 %>%
ggbarplot(x = "enrichment_method", y = "percent_rrna", add = c("mean_se"),
          position = position_dodge(),
          color = "black", palette = c("#A7A8A8", "#BBEFFA", "#C2F5D4"),
          fill = "enrichment_method",
          ylim = c(0, 100),
          order = c("Total", "Poly(A)", "RiboZero"),
          legend = "none",
          ylab = "rRNA reads (% total reads)", xlab = " ") +
  stat_pvalue_manual(
    stat.test_2018, label = "p.adj.signif", 
    tip.length = 0,
    size = 6,
    bracket.size = 0.75,
    y.position = c(95, 100, 69))
```
# Combined rRNA Plot
## Combine rRNA data from 2018 and 2019 
```{r}
enrichment_renames = c("mRNA" = "Poly(A)",
                       "Total" = "Unenriched")

full_data_counts_2018_with_meta %>%
  dplyr::rename(genotype=Strain,
                condition=Media) %>%
  bind_rows(enrich_compare_counts_with_meta) %>%
  mutate(enrichment_method=str_replace_all(enrichment_method, enrichment_renames),
         enrichment_method=factor(enrichment_method, levels = c("Unenriched", "RNaseH", "RiboZero", "Poly(A)")),
         genotype=str_replace(genotype, "H99", "WT")) %>% 
  group_by(enrichment_method, RNA_sample_num, genotype,condition,sequencing_year) %>%
  summarise(
    total_reads=sum(total_reads),
    mapped_reads=sum(mapped_reads),
    rrna_reads=sum(rrna_reads)) %>%
  mutate(ratio_rrna=rrna_reads/total_reads,
         percent_rrna=ratio_rrna*100,
         log_tranform_ratio=log10(ratio_rrna)) ->
  rrna_data_combined
```

## Make Plot
```{r include=TRUE}
set.seed(5)
fig_palette="Dark2"
xlabels <- c("Unenriched", "RNase H", "Ribo-Zero", "Poly(A)")

ggplot(data = rrna_data_combined) +
  aes(x=enrichment_method, y=percent_rrna, color=enrichment_method) +
  geom_boxplot(fill=NA, color="grey70",outlier.color = NA, width=0.5) +
  ylim(0, 100) +
  geom_jitter(width=0.3, height=0, size = 4, stroke = 1, alpha=0.5) +
  scale_colour_brewer(palette = fig_palette, guide = FALSE) +
  labs(x="Enrichment Method ", y="rRNA reads (% total reads)") +
  scale_x_discrete(labels= xlabels) +
  theme_minimal() +
  theme(text=element_text(size=10)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

ggsave(file.path(fig.dir, "Figure_1.tiff"), compression = "lzw", width=15, height=10.71, units = "cm")
```
