---
title: "Run rRNA Analysis"
output:
  html_document:
    toc: false
---


```{r load_libraries}
library(here)
library(dplyr)
library(fs)
library(rmarkdown)
library(magrittr)
library(utils)
library(callr)
```

```{r set_paths}
source("run_config.R")
delete_outdir=TRUE
```

```{r prepare_output_dir}

if (delete_outdir & dir_exists(out.dir)) {dir_delete(out.dir)}

regression_output_dir = file.path(out.dir, "full_run_html")
dir.create(regression_output_dir, recursive = TRUE)
```

```{r find_rmds}
list.files(pattern = ".Rmd") ->
  all_rmd_vector

"run_star_on_total_samples.Rmd" # should be second, but it is creating problems when knit

ordered_rmds_to_run = c(
  "download_data.Rmd",
  "make_adapter_file.Rmd",
  "qc_raw_fastqs.Rmd",
  "run_star_on_total_samples.Rmd",
  "qc_total_reads_trimmed_and_star.Rmd",
  "map_mito_rrna_genes.Rmd", 
  "generate_rnaseh_oligos.Rmd",
  "check_rnaseh_oligos.Rmd",
  "run_star_on_enrich_compare_samples.Rmd",
  "qc_enriched_trimmed_and_star.Rmd",
  "enrichment_correlation.Rmd"
  )

cat(paste("Rmds not run by this meta script:", paste(setdiff(all_rmd_vector, ordered_rmds_to_run), collapse="\n"), sep="\n"))
```

```{r run_render, eval=FALSE, include=FALSE}
#R -e "rmarkdown::render('run_full_lemur_data.Rmd',output_file='run_full_lemur_data.html')"

for (cur_rmd in ordered_rmds_to_run){
  print(cur_rmd)
  path_file(cur_rmd) %>%
    path_ext_set("html") %>%
    file.path(regression_output_dir, .) ->
    cur_out
  render(cur_rmd, output_file=cur_out, output_format="html_document")
}
```

```{r}
for (cur_rmd in ordered_rmds_to_run) {
  print(cur_rmd)
  path_file(cur_rmd) %>%
    path_ext_set("html") %>%
    file.path(regression_output_dir, .) ->
    cur_out
  # Run render in callr::r to avoid library leakage between Rmds. This fixes a problem knitting enrichment_correlation.Rmd
  callr::r(
    function(input, output_file, output_format) {
      rmarkdown::render(input = input,
                        output_file = output_file,
                        output_format = output_format)
    },
    args = list(
      input = cur_rmd,
      output_file = cur_out,
      output_format = "html_document"
    )
  )
  cat("RENDERED:", cur_out, fill = TRUE)
}
```


```{r make_igv_package, eval=FALSE, include=FALSE}
files_to_tar = c(gtf_with_mito_rrna.file, 
                 fa_for_mito_rrna.file,
                 rrna_oligos.file,
                 list.files(rrna_oligo_starout.dir, 
                            pattern = ".bam", 
                            full.names = TRUE)
                 )

tar(igv_tarball, 
    files=files_to_tar,
    compression="gzip", 
    tar = "/bin/tar")
print(igv_tarball)
```

# SessionInfo
```{r session_info}
sessionInfo()
```
